// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"context"
	"github.com/fspcons/core/models"
	"sync"
)

// Ensure, that CreateProcessorMock does implement models.CreateProcessor.
// If this is not the case, regenerate this file with moq.
var _ models.CreateProcessor[models.Validator] = &CreateProcessorMock[models.Validator]{}

// CreateProcessorMock is a mock implementation of models.CreateProcessor.
//
//	func TestSomethingThatUsesCreateProcessor(t *testing.T) {
//
//		// make and configure a mocked models.CreateProcessor
//		mockedCreateProcessor := &CreateProcessorMock{
//			ProcessFunc: func(ctx context.Context, v *V) error {
//				panic("mock out the Process method")
//			},
//		}
//
//		// use mockedCreateProcessor in code that requires models.CreateProcessor
//		// and then make assertions.
//
//	}
type CreateProcessorMock[V models.Validator] struct {
	// ProcessFunc mocks the Process method.
	ProcessFunc func(ctx context.Context, v *V) error

	// calls tracks calls to the methods.
	calls struct {
		// Process holds details about calls to the Process method.
		Process []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// V is the v argument value.
			V *V
		}
	}
	lockProcess sync.RWMutex
}

// Process calls ProcessFunc.
func (mock *CreateProcessorMock[V]) Process(ctx context.Context, v *V) error {
	if mock.ProcessFunc == nil {
		panic("CreateProcessorMock.ProcessFunc: method is nil but CreateProcessor.Process was just called")
	}
	callInfo := struct {
		Ctx context.Context
		V   *V
	}{
		Ctx: ctx,
		V:   v,
	}
	mock.lockProcess.Lock()
	mock.calls.Process = append(mock.calls.Process, callInfo)
	mock.lockProcess.Unlock()
	return mock.ProcessFunc(ctx, v)
}

// ProcessCalls gets all the calls that were made to Process.
// Check the length with:
//
//	len(mockedCreateProcessor.ProcessCalls())
func (mock *CreateProcessorMock[V]) ProcessCalls() []struct {
	Ctx context.Context
	V   *V
} {
	var calls []struct {
		Ctx context.Context
		V   *V
	}
	mock.lockProcess.RLock()
	calls = mock.calls.Process
	mock.lockProcess.RUnlock()
	return calls
}
