// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"context"
	"github.com/fspcons/core/models"
	"github.com/google/uuid"
	"sync"
)

// Ensure, that GetterMock does implement models.Getter.
// If this is not the case, regenerate this file with moq.
var _ models.Getter[any] = &GetterMock[any]{}

// GetterMock is a mock implementation of models.Getter.
//
//	func TestSomethingThatUsesGetter(t *testing.T) {
//
//		// make and configure a mocked models.Getter
//		mockedGetter := &GetterMock{
//			GetFunc: func(ctx context.Context, id uuid.UUID) (T, error) {
//				panic("mock out the Get method")
//			},
//		}
//
//		// use mockedGetter in code that requires models.Getter
//		// and then make assertions.
//
//	}
type GetterMock[T any] struct {
	// GetFunc mocks the Get method.
	GetFunc func(ctx context.Context, id uuid.UUID) (T, error)

	// calls tracks calls to the methods.
	calls struct {
		// Get holds details about calls to the Get method.
		Get []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID uuid.UUID
		}
	}
	lockGet sync.RWMutex
}

// Get calls GetFunc.
func (mock *GetterMock[T]) Get(ctx context.Context, id uuid.UUID) (T, error) {
	if mock.GetFunc == nil {
		panic("GetterMock.GetFunc: method is nil but Getter.Get was just called")
	}
	callInfo := struct {
		Ctx context.Context
		ID  uuid.UUID
	}{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockGet.Lock()
	mock.calls.Get = append(mock.calls.Get, callInfo)
	mock.lockGet.Unlock()
	return mock.GetFunc(ctx, id)
}

// GetCalls gets all the calls that were made to Get.
// Check the length with:
//
//	len(mockedGetter.GetCalls())
func (mock *GetterMock[T]) GetCalls() []struct {
	Ctx context.Context
	ID  uuid.UUID
} {
	var calls []struct {
		Ctx context.Context
		ID  uuid.UUID
	}
	mock.lockGet.RLock()
	calls = mock.calls.Get
	mock.lockGet.RUnlock()
	return calls
}
